package com.pickyeaters.logic.utils;

public class LiteralKey {
    private LiteralKey() {}

    public static final String FIELD_EATINGPREFERENCE_DISLIKEINGREDIENT = "FIELD_EATINGPREFERENCE_DISLIKEINGREDIENT";
    public static final String FIELD_EATINGPREFERENCE_ALLERGEN = "FIELD_EATINGPREFERENCE_ALLERGEN";
    public static final String FIELD_EATINGPREFERENCE_EXCLUDEDGROUP = "FIELD_EATINGPREFERENCE_EXCLUDEDGROUP";

    public static final String ASK_ADD = "ASK_ADD";
    public static final String ASK_REMOVE = "ASK_REMOVE";

    public static final String RESTAURATEUR_MANAGERESTAURANTDETAILS_RESTAURANT_CITY = "RESTAURATEUR_MANAGERESTAURANTDETAILS_RESTAURANT_CITY";
    public static final String RESTAURATEUR_MANAGERESTAURANTDETAILS_RESTAURANT_PHONE = "RESTAURATEUR_MANAGERESTAURANTDETAILS_RESTAURANT_PHONE";
    public static final String RESTAURATEUR_MANAGERESTAURANTDETAILS_RESTAURANT_ADDRESS = "RESTAURATEUR_MANAGERESTAURANTDETAILS_RESTAURANT_ADDRESS";
    public static final String RESTAURATEUR_MANAGERESTAURANTDETAILS_RESTAURANT_NAME = "RESTAURATEUR_MANAGERESTAURANTDETAILS_RESTAURANT_NAME";

    public static final String RESTAURATEUR_MANAGEMENUDETAILS_NAME = "RESTAURATEUR_MANAGEMENUDETAILS_NAME";
    public static final String RESTAURATEUR_MANAGEMENUDETAILS_DESCRIPTION = "RESTAURATEUR_MANAGEMENUDETAILS_DESCRIPTION";
    public static final String RESTAURATEUR_MANAGEMENUDETAILS_CATEGORY = "RESTAURATEUR_MANAGEMENUDETAILS_CATEGORY";
    public static final String RESTAURATEUR_MANAGEMENUDETAILS_INGREDIENTS = "RESTAURATEUR_MANAGEMENUDETAILS_INGREDIENTS";

    public static final String RESTAURATEUR_EDITDISH_ALLERGENS = "RESTAURATEUR_EDITDISH_ALLERGENS";
    public static final String RESTAURATEUR_EDITDISH_ADDINGREDIENT = "RESTAURATEUR_EDITDISH_ADDINGREDIENT";

    public static final String FIELD_DISH_ID = "FIELD_DISH_ID";
    public static final String FIELD_DISH_NAME = "FIELD_DISH_NAME";
    public static final String FIELD_DISH_DESCRIPTION = "FIELD_DISH_DESCRIPTION";
    public static final String FIELD_DISH_TYPE = "FIELD_DISH_TYPE";
    public static final String FIELD_DISH_INGREDIENT = "FIELD_DISH_INGREDIENT";
    public static final String SAVECHANGES = "SAVECHANGES";

    public static final String DEFAULT_ALERT_ERROR_TITLE = "DEFAULT_ALERT_ERROR_TITLE";
    public static final String DEFAULT_ALERT_ERROR_HEADER = "DEFAULT_ALERT_ERROR_HEADER";
    public static final String DEFAULT_ALERT_ERROR_CONTENT = "DEFAULT_ALERT_ERROR_CONTENT";
}
